In [1]:
import numpy as np
x = np.load('./0/metadata/0100.npz', mmap_mode='r')
for k in x.files:
    print(k)

intrinsic_mat
extrinsic_mat
object_poses


In [2]:
def npz_data(npz):
    query = np.load(npz)
    return query['intrinsic_mat'], query['extrinsic_mat'], query['object_poses']

In [3]:
query = np.load('./0/metadata/0100.npz')
O = query['object_poses'][2][1][:,3][:3]
S = query['object_poses'][4][1][:,3][:3]


In [6]:
query['object_poses'][4][1]

array([[ 1.96983796e-02,  6.05358303e-01, -7.95709252e-01,
        -7.94968033e+01],
       [-9.99805987e-01,  1.19268922e-02, -1.56772248e-02,
        -1.56626213e+00],
       [ 0.00000000e+00,  7.95863688e-01,  6.05475724e-01,
         6.04911690e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [53]:
def cal_LD(path):
    query = np.load(path)
    O = query['object_poses'][2][1][:,3][:3] # Origin Position
    S = query['object_poses'][4][1][:,3][:3] # Sun Position
    v = S - O
    LD = v / np.sqrt(np.sum(v**2)) # Normal Vector (Light Direction)
    return  LD

In [33]:
import os

path_dir = './dataset/0/metadata'
file_list = os.listdir(path_dir)

LD0 = []
for i in range(len(file_list)):
    path = path_dir + '/' + file_list[i]
    LD.append(cal_LD(path))
    
#print(np.array(LD).shape)

np.save('./light_direction0', LD)

In [43]:
path_dir = './dataset/135/metadata'
file_list = os.listdir(path_dir)

LD0 = []
for i in range(len(file_list)):
    path = path_dir + '/' + file_list[i]
    LD.append(cal_LD(path))
    
#print(np.array(LD).shape)

np.save('./light_direction135', LD)

[array([0., 1., 0.]),
 array([ 0.01247619,  0.9998771 , -0.00949345]),
 array([ 0.02496951,  0.99950764, -0.01899994]),
 array([ 0.03747075,  0.99889088, -0.02851246]),
 array([ 0.04997062,  0.99802661, -0.03802393]),
 array([ 0.06245986,  0.9969152 , -0.04752731]),
 array([ 0.07492916,  0.99555756, -0.05701553]),
 array([ 0.08736935,  0.99395513, -0.06648159]),
 array([ 0.09977129,  0.99210991, -0.07591855]),
 array([ 0.11212989,  0.99002371, -0.08532252]),
 array([ 0.12447471,  0.98769171, -0.09471602]),
 array([ 0.13680612,  0.9851129 , -0.10409931]),
 array([ 0.14911491,  0.98228832, -0.11346539]),
 array([ 0.16139195,  0.97921959, -0.1228073 ]),
 array([ 0.17362803,  0.97590887, -0.13211805]),
 array([ 0.18581421,  0.97235884, -0.14139083]),
 array([ 0.19794143,  0.96857275, -0.15061875]),
 array([ 0.21000114,  0.9645543 , -0.15979528]),
 array([ 0.22200513,  0.96030025, -0.16892943]),
 array([ 0.23397379,  0.95580291, -0.17803669]),
 array([ 0.24589824,  0.95106456, -0.18711031])

In [44]:
path_dir = './dataset/180/metadata'
file_list = os.listdir(path_dir)

LD0 = []
for i in range(len(file_list)):
    path = path_dir + '/' + file_list[i]
    LD.append(cal_LD(path))
    
#print(np.array(LD).shape)

np.save('./light_direction180', LD)

(200, 3)


In [ ]:
path_dir = './dataset/225/metadata'
file_list = os.listdir(path_dir)

LD0 = []
for i in range(len(file_list)):
    path = path_dir + '/' + file_list[i]
    LD.append(cal_LD(path))
    
#print(np.array(LD).shape)

np.save('./light_direction225', LD)

In [ ]:
path_dir = './dataset/270/metadata'
file_list = os.listdir(path_dir)

LD0 = []
for i in range(len(file_list)):
    path = path_dir + '/' + file_list[i]
    LD.append(cal_LD(path))
    
#print(np.array(LD).shape)

np.save('./light_direction0', LD)